import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

let packageInfo: { name: string; version: string; homepage?: string } | null =
  null;

function getPackageInfo() {
  if (!packageInfo) {
    try {
      const packageJsonPath = join(__dirname, "../../package.json");
      const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
      packageInfo = {
        name: packageJson.name || "@speria-jp/json-schema-validator-gen",
        version: packageJson.version || "unknown",
        homepage:
          packageJson.homepage ||
          "https://github.com/speria-jp/json-schema-validator-gen",
      };
    } catch {
      packageInfo = {
        name: "@speria-jp/json-schema-validator-gen",
        version: "unknown",
        homepage: "https://github.com/speria-jp/json-schema-validator-gen",
      };
    }
  }
  return packageInfo;
}

export function getGeneratedHeader(): string {
  const info = getPackageInfo();
  return [
    `// Generated by ${info.name}`,
    `// ${info.homepage}`,
    `// Do not edit manually`,
    ``,
  ].join("\n");
}
